`(
  ("xLabel" . "x-axis lab - lines")
  ("plotsList" .
   (
    (("function" . ,(lambda (x) (+ (* x 2) -2.)))
     ("range" . (-2. 2.))
     ("line-width" . "3ln")
     ("dash-style" . "11100"))
    (("function" . ,(lambda (x) (+ (* x 2) -1.)))
     ("range" . (-2. 2.)))
    (("function" . ,(lambda (x) (+ (* x 2) -0.)))
     ("range" . (-2. 2.)))
    (("function" . ,(lambda (x) (+ (* x 2) 1.)))
     ("range" . (-2. 2.)))
    (("function" . ,(lambda (x) (+ (* x 2) 2.)))
     ("range" . (-2. 2.))
     ("line-width" . "1ln")
     ("dash-style" . "10"))
    (("function" . ,(lambda (x) (+ (* x 2) 3.)))
     ("range" . (-2. 2.)))
    )))
