`(
  ("xLabel" . "x-axis lab - just a few points")
  ("sizeX" . 12)
  ("sizeY" . 8)
  ("plotsList" . (
		  (("function" . ,(lambda (x) ( - (expt x 2) 2.)))
		   ("range" . ,(list -2. 2.))
		   ("nPoints" . 9))
		  (("function" . ,(lambda (x) ( - 2. (expt x 2) )))
		   ("range" . ,(list -1. 1.))
		   ("nPoints" . 9))
		  (("function" .  ,(lambda (x) (* 3. (exp (* -8 (expt x 2))))))
		   ("range" . ,(list -2. 2.))
		   ("nPoints" . 21))
		  (("function" . ,(lambda (x) (sin (* 5 x))))
		   ("range" . ,(list -3.14 3.14))
		   ("nPoints" . 35))
		  )))
